// BEST PRACTISE - KEEP PACKAGE STRUCTURE MATCHING FOLDER STRUCTURE

package packages // YOU CAN NAME IT ANYTHING BUT IT IS RECOMMENDED TO USE THE SAME NAME AS THAT OF THE FOLDER

fun printName(name : String){
    println(name)
}